# Generated by Django 6.0.7 on 2026-07-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='pin',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
